site_name: 'Web Notes'
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
pages:
  - Home: index.md
  - Precalculus:
      - Additional Topics in Trigonometry:
          - Solving Triangles: precalc/u1-atit/l1-triangles.md
          - Vectors: precalc/u1-atit/l2-vectors.md
          - DeMoivre's Theorem and nth Roots: precalc/u1-atit/l3-roots.md
      - Sequences, Series, and Proof by Induction:
          - Sequences: precalc/u2-series/l1-sequences.md
          - Mathmatical Induction: precalc/u2-series/l2-induction.md
      - Topics in Analytical Gemometry:
          - Conics: precalc/u3-ag/l1-conics.md
          - Parametric Equations: precalc/u3-ag/l2-parametric.md
          - Polar Coordinates: precalc/u3-ag/l3-polar.md
extra_css:
    - css/custom.css
theme: windmill