site_name: 'Web Notes'
pages:
  - Home: index.md
  - CSS:
      - Bootstrap: css/bootstrap.md
  - JavaScript: 
      - DOM: js/dom.md
      - jQuery: js/jquery.md
  - Node.js:
      - Express: nodejs/express.md
  - Mongodb:
      - Mongo: mongodb/mongo.md
      - Mongoose: mongodb/mongoose.md
  - Other:
      - RESTful Routes: other/rest.md
      - Express Template: other/expressTemplate.md
theme:
  name: 'rtd-dropdown'