site_name: 'Web Notes'
pages:
  - Home: index.md
  - CSS:
      - Bootstrap: css-docs/bootstrap.md
  - JavaScript: 
      - Vanilla: js/vanilla.md
      - ES6: js/es6.md
      - DOM: js/dom.md
      - jQuery: js/jquery.md
  - Node.js:
      - Express: nodejs/express.md
  - Mongodb:
      - Mongo: mongodb/mongo.md
      - Mongoose: mongodb/mongoose.md
  - Linux:
      - Commands: linux/commands.md
  - Other:
      - RESTful Routes: other/rest.md
      - Express Template: other/expressTemplate.md
extra_css:
    - css/custom.css
theme:
    name: 'rtd-dropdown'